AllCops:
  TargetRubyVersion: 2.7
  Include:
    - '**/*.rake'
    - '**/Rakefile'
    - '**/Capfile'
    - '**/lib/**/*.rb'
    - '**/spec/**/*.rb'
  Exclude:
    - '**/*.gemspec'
    - '**/Gemfile*'
  NewCops: enable

Security/Eval:
  Enabled: false

Layout/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 20

Metrics/ClassLength:
  Max: 120

Style/RaiseArgs:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Enabled: true
  Exclude:
    - 'spec/**/*'

Metrics/ModuleLength:
  Enabled: true
  Max: 110
  Exclude:
    - 'spec/**/*'

Style/FormatStringToken:
  Enabled: false

Style/SignalException:
  Enabled: false

Naming/VariableName:
  Enabled: false

Metrics/AbcSize:
  Enabled: true
  Exclude:
    - 'lib/fielded_struct/structs/base.rb'
    - 'spec/support/**'
    - 'lib/fielded_struct/structs/base/attribute.rb'

Metrics/CyclomaticComplexity:
  Enabled: true
  Exclude:
    - 'lib/fielded_struct/structs/base.rb'
    - 'lib/fielded_struct/structs/base/attribute.rb'
