name: Publish Ruby Gem To GitHub Packages (Pushed)

on:
  push

jobs:
  build-and-push:
    name: Build And Push Gems
    uses: upbound-group/ruby-actions/.github/workflows/reusable_push_gems.yml@main  # locking to `main` branch for latest updates for now
    secrets: inherit
    permissions:
      contents: read
      packages: write
    with:
      registry-url: "https://rubygems.pkg.github.com/acima-credit"
      use-github-token-as-bearer-token: true

